###
POST http://localhost:3001/api/auth/send-code
Content-Type: application/json
Authorization: eyJhbGciOiJSUzI1NiIsImtpZCI6IjA1NTc3MjZmYWIxMjMxZmEyZGNjNTcyMWExMDgzZGE2ODBjNGE3M2YiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZmx1ZW5jY3l3ZWIiLCJhdWQiOiJmbHVlbmNjeXdlYiIsImF1dGhfdGltZSI6MTc1OTIxNDk1MiwidXNlcl9pZCI6IjJ5MUpKQnZybEJPbUJIWm5BRFRIT0JDb2VHQTIiLCJzdWIiOiIyeTFKSkJ2cmxCT21CSFpuQURUSE9CQ29lR0EyIiwiaWF0IjoxNzU5MjE0OTUyLCJleHAiOjE3NTkyMTg1NTIsImVtYWlsIjoicmVobWFuc2FpZm1vaGRAeWFob28uY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsicmVobWFuc2FpZm1vaGRAeWFob28uY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.SmrD_R_Euu4O9vvdjk1hXgi9hYiWiSk6Xrn1DDGOqRRYBRoFezAiPmIaqYoxBIKJ5TcQKEqTYzwvBWJ_EGL8OHnMvs70BK2lyzgh7KLftUdtNqYUfYt_fqPVGJ5tG9oMGopKd8NDyBfcCIReq-2Kn8BIzrbvNBx6nukZMplOvfOaG50InKL6qJYGmunMmV-198QSUybVgSxKIp51MEJgGrBKC8hBJ2zEZn8js9l0b2SFHDp5vFPQq1RwDo_86OnUBu_7izf3JE128gFmwYEbzpJC2TvEDI7EavhtoHSkFRBXRW5y99UKSl_2OdE_fNdHycBrVJPx_nhvTr1WUC_bmQ

{
    "email": "rehmansaifmohd@yahoo.com",
    "username": "rehmansaifmohd@yahoo.com"
}

